# render.yaml
services:
  - type: web
    name: berriberri-teknno
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m gunicorn app:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.4"